import os
from snakemake.utils import min_version
min_version('6.13.1')

configfile: '../config.yaml'

rule all:
    input:
        os.path.join(config['base_dir'], config['data_dir_qc'], 'qc_report_fastq.html')

rule qualityControl:
    input:
        os.path.join(config['base_dir'], config['data_dir_fastq'], '{file}.raw.fq.gz')
    output:
        os.path.join(config['base_dir'], config['data_dir_qc'], '{file}_fastqc.html')
    params:
        outputpath = os.path.join(config['base_dir'], config['data_dir_qc'])
    shell:
        'fastqc -o {params.outputpath} {input}''
            
rule summaryReport:
    input:
        expand(os.path.join(config['base_dir'], config['data_dir_qc'], '{file}_fastqc.html'), file = id)
    output:
        os.path.join(config['base_dir'], config['data_dir_qc'], 'qc_report_fastq.html')
    params:
        path_qc_dir = os.path.join(config['base_dir'], config['data_dir_qc'])
    shell:
        "multiqc {params.path_qc_dir} --filename {output}"